# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfs.pb import dfs_pb2 as dfs_dot_pb_dot_dfs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfs/pb/dfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """=============================================================================
    CONTROLSERVICE — Plano de Controle
    =============================================================================

    Implementado pelo coordenador. Responsável por:
    - registro e supervisão dos nós (RegisterNode, Heartbeat)
    - autorização de operações da CLI (RequestUpload, RequestDownload)
    - persistência de metadados após operações concluídas (ConfirmUpload)
    - operações puramente de controle (DeleteFile, ListFiles)

    IMPORTANTE: NENHUMA RPC deste serviço transporta bytes de arquivos de
    usuário. Todo o conteúdo aqui é metadado leve.

    =============================================================================

    ---------- Registro e supervisão de nós ----------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/dfs.v1.ControlService/RegisterNode',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dfs.v1.ControlService/Heartbeat',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RequestUpload = channel.unary_unary(
                '/dfs.v1.ControlService/RequestUpload',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.RequestUploadRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.RequestUploadResponse.FromString,
                _registered_method=True)
        self.ConfirmUpload = channel.unary_unary(
                '/dfs.v1.ControlService/ConfirmUpload',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.ConfirmUploadRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestDownload = channel.unary_unary(
                '/dfs.v1.ControlService/RequestDownload',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.RequestDownloadRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.RequestDownloadResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/dfs.v1.ControlService/DeleteFile',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/dfs.v1.ControlService/ListFiles',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """=============================================================================
    CONTROLSERVICE — Plano de Controle
    =============================================================================

    Implementado pelo coordenador. Responsável por:
    - registro e supervisão dos nós (RegisterNode, Heartbeat)
    - autorização de operações da CLI (RequestUpload, RequestDownload)
    - persistência de metadados após operações concluídas (ConfirmUpload)
    - operações puramente de controle (DeleteFile, ListFiles)

    IMPORTANTE: NENHUMA RPC deste serviço transporta bytes de arquivos de
    usuário. Todo o conteúdo aqui é metadado leve.

    =============================================================================

    ---------- Registro e supervisão de nós ----------
    """

    def RegisterNode(self, request, context):
        """Chamada por um nó ao iniciar, para se anunciar ao coordenador.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Chamada periodicamente por cada nó (a cada ~2s). Carrega também o
        inventário de chunks armazenados ("block report"). Padrão herdado do HDFS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestUpload(self, request, context):
        """---------- Autorização de operações de dados ----------

        Etapa 1 do PUT: a CLI pede permissão para enviar um arquivo. O coordenador
        escolhe o ingress, reserva um upload_id, e devolve o endereço do ingress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmUpload(self, request, context):
        """Etapa final do PUT: o INGRESS (não a CLI) confirma ao coordenador que o
        upload foi concluído, e informa quais chunks foram criados e em quais nós.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDownload(self, request, context):
        """Etapa 1 do GET: a CLI pede para baixar um arquivo. O coordenador escolhe
        o egress (por localidade) e devolve o endereço.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """---------- Operações de controle puras (sem bytes) ----------

        Deleta um arquivo. O coordenador remove os metadados e dispara comandos
        DeleteChunk em paralelo para todas as réplicas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Lista arquivos conhecidos pelo coordenador.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.RegisterNodeRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.HeartbeatRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RequestUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestUpload,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.RequestUploadRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.RequestUploadResponse.SerializeToString,
            ),
            'ConfirmUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmUpload,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.ConfirmUploadRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.Ack.SerializeToString,
            ),
            'RequestDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDownload,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.RequestDownloadRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.RequestDownloadResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.DeleteFileRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.Ack.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.ListFilesRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """=============================================================================
    CONTROLSERVICE — Plano de Controle
    =============================================================================

    Implementado pelo coordenador. Responsável por:
    - registro e supervisão dos nós (RegisterNode, Heartbeat)
    - autorização de operações da CLI (RequestUpload, RequestDownload)
    - persistência de metadados após operações concluídas (ConfirmUpload)
    - operações puramente de controle (DeleteFile, ListFiles)

    IMPORTANTE: NENHUMA RPC deste serviço transporta bytes de arquivos de
    usuário. Todo o conteúdo aqui é metadado leve.

    =============================================================================

    ---------- Registro e supervisão de nós ----------
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/RegisterNode',
            dfs_dot_pb_dot_dfs__pb2.RegisterNodeRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/Heartbeat',
            dfs_dot_pb_dot_dfs__pb2.HeartbeatRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/RequestUpload',
            dfs_dot_pb_dot_dfs__pb2.RequestUploadRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.RequestUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/ConfirmUpload',
            dfs_dot_pb_dot_dfs__pb2.ConfirmUploadRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/RequestDownload',
            dfs_dot_pb_dot_dfs__pb2.RequestDownloadRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.RequestDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/DeleteFile',
            dfs_dot_pb_dot_dfs__pb2.DeleteFileRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ControlService/ListFiles',
            dfs_dot_pb_dot_dfs__pb2.ListFilesRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataServiceStub(object):
    """=============================================================================
    DATASERVICE — Plano de Dados (interface com a CLI)
    =============================================================================

    Implementado pelos NÓS. A CLI fala com este serviço APENAS depois de já
    ter conversado com o coordenador no ControlService e recebido o endereço
    do nó certo (ingress no PUT, egress no GET). Tudo aqui é STREAMING.

    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/dfs.v1.DataService/UploadFile',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.UploadChunk.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.UploadResult.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/dfs.v1.DataService/DownloadFile',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.DownloadStart.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.DownloadChunk.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """=============================================================================
    DATASERVICE — Plano de Dados (interface com a CLI)
    =============================================================================

    Implementado pelos NÓS. A CLI fala com este serviço APENAS depois de já
    ter conversado com o coordenador no ControlService e recebido o endereço
    do nó certo (ingress no PUT, egress no GET). Tudo aqui é STREAMING.

    =============================================================================

    """

    def UploadFile(self, request_iterator, context):
        """PUT (client-streaming): a CLI envia uma sequência de UploadChunk; ao final,
        o ingress responde com UploadResult.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """GET (server-streaming): a CLI manda um DownloadStart e recebe uma sequência
        de DownloadChunk até o stream fechar.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.UploadChunk.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.UploadResult.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.DownloadStart.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.DownloadChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """=============================================================================
    DATASERVICE — Plano de Dados (interface com a CLI)
    =============================================================================

    Implementado pelos NÓS. A CLI fala com este serviço APENAS depois de já
    ter conversado com o coordenador no ControlService e recebido o endereço
    do nó certo (ingress no PUT, egress no GET). Tudo aqui é STREAMING.

    =============================================================================

    """

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfs.v1.DataService/UploadFile',
            dfs_dot_pb_dot_dfs__pb2.UploadChunk.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.UploadResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfs.v1.DataService/DownloadFile',
            dfs_dot_pb_dot_dfs__pb2.DownloadStart.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.DownloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicationServiceStub(object):
    """=============================================================================
    REPLICATIONSERVICE — Comunicação entre Nós
    =============================================================================

    Implementado pelos NÓS. Usado por OUTROS NÓS (e pelo coordenador para
    operações administrativas como deleção).

    1. Ingress chama StoreChunk nas outras réplicas para fan-out durante o PUT.
    2. Egress chama FetchChunk nos peers para buscar chunks que não tem.
    3. DeleteChunk: chamada pelo coordenador para apagar um chunk específico.
    4. ListChunks: diagnóstico / validação cruzada com os metadados.

    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreChunk = channel.stream_unary(
                '/dfs.v1.ReplicationService/StoreChunk',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.StoreChunkRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.StoreChunkResponse.FromString,
                _registered_method=True)
        self.FetchChunk = channel.unary_stream(
                '/dfs.v1.ReplicationService/FetchChunk',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.FetchChunkRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.FetchChunkResponse.FromString,
                _registered_method=True)
        self.DeleteChunk = channel.unary_unary(
                '/dfs.v1.ReplicationService/DeleteChunk',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.DeleteChunkRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
                _registered_method=True)
        self.ListChunks = channel.unary_unary(
                '/dfs.v1.ReplicationService/ListChunks',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.ListChunksRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.ListChunksResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """=============================================================================
    REPLICATIONSERVICE — Comunicação entre Nós
    =============================================================================

    Implementado pelos NÓS. Usado por OUTROS NÓS (e pelo coordenador para
    operações administrativas como deleção).

    1. Ingress chama StoreChunk nas outras réplicas para fan-out durante o PUT.
    2. Egress chama FetchChunk nos peers para buscar chunks que não tem.
    3. DeleteChunk: chamada pelo coordenador para apagar um chunk específico.
    4. ListChunks: diagnóstico / validação cruzada com os metadados.

    =============================================================================

    """

    def StoreChunk(self, request_iterator, context):
        """PUT lado-réplica: outro nó (o ingress) envia este chunk para ser armazenado.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchChunk(self, request, context):
        """GET lado-peer: outro nó (o egress) pede um chunk específico.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChunk(self, request, context):
        """Apaga um chunk específico do disco local.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChunks(self, request, context):
        """Lista os chunks armazenados localmente.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreChunk,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.StoreChunkRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.StoreChunkResponse.SerializeToString,
            ),
            'FetchChunk': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchChunk,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.FetchChunkRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.FetchChunkResponse.SerializeToString,
            ),
            'DeleteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChunk,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.DeleteChunkRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.Ack.SerializeToString,
            ),
            'ListChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChunks,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.ListChunksRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.ListChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.v1.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.v1.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """=============================================================================
    REPLICATIONSERVICE — Comunicação entre Nós
    =============================================================================

    Implementado pelos NÓS. Usado por OUTROS NÓS (e pelo coordenador para
    operações administrativas como deleção).

    1. Ingress chama StoreChunk nas outras réplicas para fan-out durante o PUT.
    2. Egress chama FetchChunk nos peers para buscar chunks que não tem.
    3. DeleteChunk: chamada pelo coordenador para apagar um chunk específico.
    4. ListChunks: diagnóstico / validação cruzada com os metadados.

    =============================================================================

    """

    @staticmethod
    def StoreChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfs.v1.ReplicationService/StoreChunk',
            dfs_dot_pb_dot_dfs__pb2.StoreChunkRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.StoreChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfs.v1.ReplicationService/FetchChunk',
            dfs_dot_pb_dot_dfs__pb2.FetchChunkRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.FetchChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ReplicationService/DeleteChunk',
            dfs_dot_pb_dot_dfs__pb2.DeleteChunkRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.ReplicationService/ListChunks',
            dfs_dot_pb_dot_dfs__pb2.ListChunksRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.ListChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
