# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfs.pb import dfs_pb2 as dfs_dot_pb_dot_dfs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfs/pb/dfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DFSServiceStub(object):
    """grpc
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessChunk = channel.unary_unary(
                '/dfs.v1.DFSService/ProcessChunk',
                request_serializer=dfs_dot_pb_dot_dfs__pb2.FileRequest.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.FileResponse.FromString,
                _registered_method=True)


class DFSServiceServicer(object):
    """grpc
    """

    def ProcessChunk(self, request, context):
        """O Coordenador chama essa função no Nó de Armazenamento
        AGORA SIM, USANDO OS NOMES CORRETOS:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessChunk,
                    request_deserializer=dfs_dot_pb_dot_dfs__pb2.FileRequest.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.v1.DFSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.v1.DFSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DFSService(object):
    """grpc
    """

    @staticmethod
    def ProcessChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.v1.DFSService/ProcessChunk',
            dfs_dot_pb_dot_dfs__pb2.FileRequest.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
