# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfs.pb import dataplane_pb2 as dfs_dot_pb_dot_dataplane__pb2
from dfs.pb import dfs_pb2 as dfs_dot_pb_dot_dfs__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfs/pb/dataplane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataPlaneServiceStub:
    """Serviço INTERNO do plano de dados, exposto pelos NÓS (no mesmo servidor/porta
    do DataService) e chamado pela CLI imediatamente ANTES de abrir o stream.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetUploadPlan = channel.unary_unary(
                '/dfs.dataplane.DataPlaneService/SetUploadPlan',
                request_serializer=dfs_dot_pb_dot_dataplane__pb2.UploadPlan.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
                _registered_method=True)
        self.SetDownloadPlan = channel.unary_unary(
                '/dfs.dataplane.DataPlaneService/SetDownloadPlan',
                request_serializer=dfs_dot_pb_dot_dataplane__pb2.DownloadPlan.SerializeToString,
                response_deserializer=dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
                _registered_method=True)


class DataPlaneServiceServicer:
    """Serviço INTERNO do plano de dados, exposto pelos NÓS (no mesmo servidor/porta
    do DataService) e chamado pela CLI imediatamente ANTES de abrir o stream.
    """

    def SetUploadPlan(self, request, context):
        """PUT: a CLI entrega ao ingress o plano do upload antes do UploadFile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDownloadPlan(self, request, context):
        """GET: a CLI entrega ao egress o plano do download antes do DownloadFile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetUploadPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUploadPlan,
                    request_deserializer=dfs_dot_pb_dot_dataplane__pb2.UploadPlan.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.Ack.SerializeToString,
            ),
            'SetDownloadPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDownloadPlan,
                    request_deserializer=dfs_dot_pb_dot_dataplane__pb2.DownloadPlan.FromString,
                    response_serializer=dfs_dot_pb_dot_dfs__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.dataplane.DataPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.dataplane.DataPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataPlaneService:
    """Serviço INTERNO do plano de dados, exposto pelos NÓS (no mesmo servidor/porta
    do DataService) e chamado pela CLI imediatamente ANTES de abrir o stream.
    """

    @staticmethod
    def SetUploadPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.dataplane.DataPlaneService/SetUploadPlan',
            dfs_dot_pb_dot_dataplane__pb2.UploadPlan.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDownloadPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.dataplane.DataPlaneService/SetDownloadPlan',
            dfs_dot_pb_dot_dataplane__pb2.DownloadPlan.SerializeToString,
            dfs_dot_pb_dot_dfs__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
