# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs/pb/dataplane.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'dfs/pb/dataplane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfs.pb import dfs_pb2 as dfs_dot_pb_dot_dfs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x66s/pb/dataplane.proto\x12\rdfs.dataplane\x1a\x10\x64\x66s/pb/dfs.proto\"a\n\nUploadPlan\x12\x11\n\tupload_id\x18\x01 \x01(\t\x12\x18\n\x10total_size_bytes\x18\x02 \x01(\x03\x12&\n\x06\x63hunks\x18\x03 \x03(\x0b\x32\x16.dfs.v1.ChunkPlacement\"e\n\x0c\x44ownloadPlan\x12\x13\n\x0b\x64ownload_id\x18\x01 \x01(\t\x12\x18\n\x10total_size_bytes\x18\x02 \x01(\x03\x12&\n\x06\x63hunks\x18\x03 \x03(\x0b\x32\x16.dfs.v1.ChunkPlacement2\x88\x01\n\x10\x44\x61taPlaneService\x12\x37\n\rSetUploadPlan\x12\x19.dfs.dataplane.UploadPlan\x1a\x0b.dfs.v1.Ack\x12;\n\x0fSetDownloadPlan\x12\x1b.dfs.dataplane.DownloadPlan\x1a\x0b.dfs.v1.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs.pb.dataplane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADPLAN']._serialized_start=59
  _globals['_UPLOADPLAN']._serialized_end=156
  _globals['_DOWNLOADPLAN']._serialized_start=158
  _globals['_DOWNLOADPLAN']._serialized_end=259
  _globals['_DATAPLANESERVICE']._serialized_start=262
  _globals['_DATAPLANESERVICE']._serialized_end=398
# @@protoc_insertion_point(module_scope)
